project_id = "hpkrccllgbepuiilkrlz"

[functions.chat]
verify_jwt = false

[functions.research-assistant]
verify_jwt = false

[functions.provision-workspace]
verify_jwt = true

[functions.notify-role-change]
verify_jwt = false

[functions.notify-role-request]
verify_jwt = false
